### ISSUE TITLE
Heists are too easy to win

### ISSUE THREAD

**Issue by kenny2810** [lorddusk/Bot#5]
When: Last 2 days

Summary: The amount of times Heists fail is too low.

More Details: The chance to fail a Heist is too low. One example is that in the last 2 days Sixkiller5 has managed to beat 1 million kinis. Before it was introduced the highest amount was in the range of 30k-40k. I have viewed a total of 7 heists now, and so far only one has failed. This has lead to people abusing the system by betting hundreds of thousands and gain 3 times the amount a majority of the time. 

Solution: Try to lower the winning probablity? 

Shoot me a message on twitter if ya need any more info.

**Comment by lorddusk** [comment]
Does he only do them alone? And if no, how many people are in those heists?

**Comment by kenny2810** [comment]
The majority of people active in chat take part. Id say around 20 of us in one go (The heist amount usually gets tripled)

**Comment by lorddusk** [comment]
That's a win chance of lower then 50% Which seems fine by me...

**Comment by kenny2810** [comment]
Ok then you have the final say on things

**Comment by lorddusk** [comment]
Well, I have anyway...
This particular is not an issue for me, It's one for rune. The command to
start a heist is for moderator level and higher.

So this is a typical example of mods abusing a command.

**Comment by kenny2810** [comment]
Issue closed then I guess
